name: cf workers

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      # Biarkan Wrangler yang menjalankan [build] -> worker-build.
      # TUGAS kita: pastikan Rust + target WASM tersedia sebelum deploy.
      - name: Build & Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # optional kalau account_id sudah di wrangler.toml; kalau mau di sini:
          # accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: production
          command: deploy --env production --verbose
          preCommands: |
            # Install Rust toolchain
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            . "$HOME/.cargo/env"
            rustup target add wasm32-unknown-unknown
